In [1]:
A = [ 1.0 2.0 ; 3.0 4.0 ]
y = ones(2, 1)

det(A)

-2.0

In [2]:
A_inv = inv(A)

2x2 Array{Float64,2}:
 -2.0   1.0
  1.5  -0.5

In [3]:
x = A_inv * y

2x1 Array{Float64,2}:
 -1.0
  1.0

In [4]:
A * x

2x1 Array{Float64,2}:
 1.0
 1.0

In [5]:
A \ y

2x1 Array{Float64,2}:
 -1.0
  1.0

In [7]:
evals, evecs = eig(A)
evals

2-element Array{Float64,1}:
 -0.372281
  5.37228 

In [8]:
evecs

2x2 Array{Float64,2}:
 -0.824565  -0.415974
  0.565767  -0.909377